//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteFiel.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:51390/Servicios/ServiciosImagen.asmx")]
        public string ClienteFiel_WS_ServiciosImagen_ServiciosImagen {
            get {
                return ((string)(this["ClienteFiel_WS_ServiciosImagen_ServiciosImagen"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:51390/Servicios/ServiciosTipoidentificacion.asmx")]
        public string ClienteFiel_WS_ServiciosTipoidentificacion_ServiciosTipoidentificacion {
            get {
                return ((string)(this["ClienteFiel_WS_ServiciosTipoidentificacion_ServiciosTipoidentificacion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:51390/Servicios/ServiciosTiporedsocial.asmx")]
        public string ClienteFiel_WS_ServiciosTiporedsocial_ServiciosTiporedsocial {
            get {
                return ((string)(this["ClienteFiel_WS_ServiciosTiporedsocial_ServiciosTiporedsocial"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:51390/Servicios/ServiciosTipoactividad.asmx")]
        public string ClienteFiel_WS_ServiciosTipoactividad_ServiciosTipoactividad {
            get {
                return ((string)(this["ClienteFiel_WS_ServiciosTipoactividad_ServiciosTipoactividad"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:51390/Servicios/ServiciosError.asmx")]
        public string ClienteFiel_WS_ServiciosError_ServiciosError {
            get {
                return ((string)(this["ClienteFiel_WS_ServiciosError_ServiciosError"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:51390/Servicios/ServiciosTipoproducto.asmx")]
        public string ClienteFiel_WS_ServiciosTipoproducto_ServiciosTipoproducto {
            get {
                return ((string)(this["ClienteFiel_WS_ServiciosTipoproducto_ServiciosTipoproducto"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:51390/Servicios/ServiciosDepartamento.asmx")]
        public string ClienteFiel_WS_ServiciosDepartamento_ServiciosDepartamento {
            get {
                return ((string)(this["ClienteFiel_WS_ServiciosDepartamento_ServiciosDepartamento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:51390/Servicios/ServiciosMunicipio.asmx")]
        public string ClienteFiel_WS_ServiciosMunicipio_ServiciosMunicipio {
            get {
                return ((string)(this["ClienteFiel_WS_ServiciosMunicipio_ServiciosMunicipio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:51390/Servicios/ServiciosViewempresa.asmx")]
        public string ClienteFiel_WS_ServiciosViewempresa_ServiciosViewempresa {
            get {
                return ((string)(this["ClienteFiel_WS_ServiciosViewempresa_ServiciosViewempresa"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:51390/Servicios/ServiciosEmpresa.asmx")]
        public string ClienteFiel_WS_ServiciosEmpresa_ServiciosEmpresa {
            get {
                return ((string)(this["ClienteFiel_WS_ServiciosEmpresa_ServiciosEmpresa"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:51390/Servicios/ServiciosProducto.asmx")]
        public string ClienteFiel_WS_ServiciosProducto_ServiciosProducto {
            get {
                return ((string)(this["ClienteFiel_WS_ServiciosProducto_ServiciosProducto"]));
            }
        }
    }
}
