//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ClienteFiel.WS_ServiciosViewproducto {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiciosViewproductoSoap", Namespace="http://tempuri.org/")]
    public partial class ServiciosViewproducto : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private Autenticacion autenticacionValueField;
        
        private System.Threading.SendOrPostCallback crearViewproductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback editarViewproductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarPrimeroViewproductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarViewproductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarPaginacionViewproductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarViewproductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarPaginacionViewproductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback contarBusquedaViewproductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarViewproductoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiciosViewproducto() {
            this.Url = global::ClienteFiel.Properties.Settings.Default.ClienteFiel_WS_ServiciosViewproducto_ServiciosViewproducto;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public Autenticacion AutenticacionValue {
            get {
                return this.autenticacionValueField;
            }
            set {
                this.autenticacionValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event crearViewproductoCompletedEventHandler crearViewproductoCompleted;
        
        /// <remarks/>
        public event editarViewproductoCompletedEventHandler editarViewproductoCompleted;
        
        /// <remarks/>
        public event buscarPrimeroViewproductoCompletedEventHandler buscarPrimeroViewproductoCompleted;
        
        /// <remarks/>
        public event buscarViewproductoCompletedEventHandler buscarViewproductoCompleted;
        
        /// <remarks/>
        public event buscarPaginacionViewproductoCompletedEventHandler buscarPaginacionViewproductoCompleted;
        
        /// <remarks/>
        public event listarViewproductoCompletedEventHandler listarViewproductoCompleted;
        
        /// <remarks/>
        public event listarPaginacionViewproductoCompletedEventHandler listarPaginacionViewproductoCompleted;
        
        /// <remarks/>
        public event contarBusquedaViewproductoCompletedEventHandler contarBusquedaViewproductoCompleted;
        
        /// <remarks/>
        public event eliminarViewproductoCompletedEventHandler eliminarViewproductoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/crearViewproducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Viewproducto crearViewproducto(Viewproducto obj) {
            object[] results = this.Invoke("crearViewproducto", new object[] {
                        obj});
            return ((Viewproducto)(results[0]));
        }
        
        /// <remarks/>
        public void crearViewproductoAsync(Viewproducto obj) {
            this.crearViewproductoAsync(obj, null);
        }
        
        /// <remarks/>
        public void crearViewproductoAsync(Viewproducto obj, object userState) {
            if ((this.crearViewproductoOperationCompleted == null)) {
                this.crearViewproductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OncrearViewproductoOperationCompleted);
            }
            this.InvokeAsync("crearViewproducto", new object[] {
                        obj}, this.crearViewproductoOperationCompleted, userState);
        }
        
        private void OncrearViewproductoOperationCompleted(object arg) {
            if ((this.crearViewproductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.crearViewproductoCompleted(this, new crearViewproductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/editarViewproducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool editarViewproducto(Viewproducto obj) {
            object[] results = this.Invoke("editarViewproducto", new object[] {
                        obj});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void editarViewproductoAsync(Viewproducto obj) {
            this.editarViewproductoAsync(obj, null);
        }
        
        /// <remarks/>
        public void editarViewproductoAsync(Viewproducto obj, object userState) {
            if ((this.editarViewproductoOperationCompleted == null)) {
                this.editarViewproductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OneditarViewproductoOperationCompleted);
            }
            this.InvokeAsync("editarViewproducto", new object[] {
                        obj}, this.editarViewproductoOperationCompleted, userState);
        }
        
        private void OneditarViewproductoOperationCompleted(object arg) {
            if ((this.editarViewproductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.editarViewproductoCompleted(this, new editarViewproductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarPrimeroViewproducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Viewproducto buscarPrimeroViewproducto(Viewproducto obj) {
            object[] results = this.Invoke("buscarPrimeroViewproducto", new object[] {
                        obj});
            return ((Viewproducto)(results[0]));
        }
        
        /// <remarks/>
        public void buscarPrimeroViewproductoAsync(Viewproducto obj) {
            this.buscarPrimeroViewproductoAsync(obj, null);
        }
        
        /// <remarks/>
        public void buscarPrimeroViewproductoAsync(Viewproducto obj, object userState) {
            if ((this.buscarPrimeroViewproductoOperationCompleted == null)) {
                this.buscarPrimeroViewproductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarPrimeroViewproductoOperationCompleted);
            }
            this.InvokeAsync("buscarPrimeroViewproducto", new object[] {
                        obj}, this.buscarPrimeroViewproductoOperationCompleted, userState);
        }
        
        private void OnbuscarPrimeroViewproductoOperationCompleted(object arg) {
            if ((this.buscarPrimeroViewproductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarPrimeroViewproductoCompleted(this, new buscarPrimeroViewproductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarViewproducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Viewproducto[] buscarViewproducto(Viewproducto obj) {
            object[] results = this.Invoke("buscarViewproducto", new object[] {
                        obj});
            return ((Viewproducto[])(results[0]));
        }
        
        /// <remarks/>
        public void buscarViewproductoAsync(Viewproducto obj) {
            this.buscarViewproductoAsync(obj, null);
        }
        
        /// <remarks/>
        public void buscarViewproductoAsync(Viewproducto obj, object userState) {
            if ((this.buscarViewproductoOperationCompleted == null)) {
                this.buscarViewproductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarViewproductoOperationCompleted);
            }
            this.InvokeAsync("buscarViewproducto", new object[] {
                        obj}, this.buscarViewproductoOperationCompleted, userState);
        }
        
        private void OnbuscarViewproductoOperationCompleted(object arg) {
            if ((this.buscarViewproductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarViewproductoCompleted(this, new buscarViewproductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarPaginacionViewproducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Viewproducto[] buscarPaginacionViewproducto(Viewproducto obj, int pag, int numReg) {
            object[] results = this.Invoke("buscarPaginacionViewproducto", new object[] {
                        obj,
                        pag,
                        numReg});
            return ((Viewproducto[])(results[0]));
        }
        
        /// <remarks/>
        public void buscarPaginacionViewproductoAsync(Viewproducto obj, int pag, int numReg) {
            this.buscarPaginacionViewproductoAsync(obj, pag, numReg, null);
        }
        
        /// <remarks/>
        public void buscarPaginacionViewproductoAsync(Viewproducto obj, int pag, int numReg, object userState) {
            if ((this.buscarPaginacionViewproductoOperationCompleted == null)) {
                this.buscarPaginacionViewproductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarPaginacionViewproductoOperationCompleted);
            }
            this.InvokeAsync("buscarPaginacionViewproducto", new object[] {
                        obj,
                        pag,
                        numReg}, this.buscarPaginacionViewproductoOperationCompleted, userState);
        }
        
        private void OnbuscarPaginacionViewproductoOperationCompleted(object arg) {
            if ((this.buscarPaginacionViewproductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarPaginacionViewproductoCompleted(this, new buscarPaginacionViewproductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarViewproducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Viewproducto[] listarViewproducto() {
            object[] results = this.Invoke("listarViewproducto", new object[0]);
            return ((Viewproducto[])(results[0]));
        }
        
        /// <remarks/>
        public void listarViewproductoAsync() {
            this.listarViewproductoAsync(null);
        }
        
        /// <remarks/>
        public void listarViewproductoAsync(object userState) {
            if ((this.listarViewproductoOperationCompleted == null)) {
                this.listarViewproductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarViewproductoOperationCompleted);
            }
            this.InvokeAsync("listarViewproducto", new object[0], this.listarViewproductoOperationCompleted, userState);
        }
        
        private void OnlistarViewproductoOperationCompleted(object arg) {
            if ((this.listarViewproductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarViewproductoCompleted(this, new listarViewproductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarPaginacionViewproducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Viewproducto[] listarPaginacionViewproducto(int pag, int numReg) {
            object[] results = this.Invoke("listarPaginacionViewproducto", new object[] {
                        pag,
                        numReg});
            return ((Viewproducto[])(results[0]));
        }
        
        /// <remarks/>
        public void listarPaginacionViewproductoAsync(int pag, int numReg) {
            this.listarPaginacionViewproductoAsync(pag, numReg, null);
        }
        
        /// <remarks/>
        public void listarPaginacionViewproductoAsync(int pag, int numReg, object userState) {
            if ((this.listarPaginacionViewproductoOperationCompleted == null)) {
                this.listarPaginacionViewproductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarPaginacionViewproductoOperationCompleted);
            }
            this.InvokeAsync("listarPaginacionViewproducto", new object[] {
                        pag,
                        numReg}, this.listarPaginacionViewproductoOperationCompleted, userState);
        }
        
        private void OnlistarPaginacionViewproductoOperationCompleted(object arg) {
            if ((this.listarPaginacionViewproductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarPaginacionViewproductoCompleted(this, new listarPaginacionViewproductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/contarBusquedaViewproducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int contarBusquedaViewproducto(Viewproducto obj) {
            object[] results = this.Invoke("contarBusquedaViewproducto", new object[] {
                        obj});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void contarBusquedaViewproductoAsync(Viewproducto obj) {
            this.contarBusquedaViewproductoAsync(obj, null);
        }
        
        /// <remarks/>
        public void contarBusquedaViewproductoAsync(Viewproducto obj, object userState) {
            if ((this.contarBusquedaViewproductoOperationCompleted == null)) {
                this.contarBusquedaViewproductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OncontarBusquedaViewproductoOperationCompleted);
            }
            this.InvokeAsync("contarBusquedaViewproducto", new object[] {
                        obj}, this.contarBusquedaViewproductoOperationCompleted, userState);
        }
        
        private void OncontarBusquedaViewproductoOperationCompleted(object arg) {
            if ((this.contarBusquedaViewproductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.contarBusquedaViewproductoCompleted(this, new contarBusquedaViewproductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/eliminarViewproducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool eliminarViewproducto(Viewproducto obj) {
            object[] results = this.Invoke("eliminarViewproducto", new object[] {
                        obj});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void eliminarViewproductoAsync(Viewproducto obj) {
            this.eliminarViewproductoAsync(obj, null);
        }
        
        /// <remarks/>
        public void eliminarViewproductoAsync(Viewproducto obj, object userState) {
            if ((this.eliminarViewproductoOperationCompleted == null)) {
                this.eliminarViewproductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarViewproductoOperationCompleted);
            }
            this.InvokeAsync("eliminarViewproducto", new object[] {
                        obj}, this.eliminarViewproductoOperationCompleted, userState);
        }
        
        private void OneliminarViewproductoOperationCompleted(object arg) {
            if ((this.eliminarViewproductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarViewproductoCompleted(this, new eliminarViewproductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class Autenticacion : System.Web.Services.Protocols.SoapHeader {
        
        private string usuarioField;
        
        private string contrasenaField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <comentarios/>
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <comentarios/>
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                this.contrasenaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Viewproducto {
        
        private long iD_PRODUCTOField;
        
        private long iD_IMAGENField;
        
        private long iD_TIPO_PRODUCTOField;
        
        private long iD_EMPRESAField;
        
        private string nOM_PRODUCTOField;
        
        private long pRECIOField;
        
        private string dESCRIPCIONField;
        
        private byte[] iMAGENField;
        
        private string nOM_TIPO_PRODUCTOField;
        
        private string nITField;
        
        private string rAZON_SOCIALField;
        
        private string sUCURSALField;
        
        /// <comentarios/>
        public long ID_PRODUCTO {
            get {
                return this.iD_PRODUCTOField;
            }
            set {
                this.iD_PRODUCTOField = value;
            }
        }
        
        /// <comentarios/>
        public long ID_IMAGEN {
            get {
                return this.iD_IMAGENField;
            }
            set {
                this.iD_IMAGENField = value;
            }
        }
        
        /// <comentarios/>
        public long ID_TIPO_PRODUCTO {
            get {
                return this.iD_TIPO_PRODUCTOField;
            }
            set {
                this.iD_TIPO_PRODUCTOField = value;
            }
        }
        
        /// <comentarios/>
        public long ID_EMPRESA {
            get {
                return this.iD_EMPRESAField;
            }
            set {
                this.iD_EMPRESAField = value;
            }
        }
        
        /// <comentarios/>
        public string NOM_PRODUCTO {
            get {
                return this.nOM_PRODUCTOField;
            }
            set {
                this.nOM_PRODUCTOField = value;
            }
        }
        
        /// <comentarios/>
        public long PRECIO {
            get {
                return this.pRECIOField;
            }
            set {
                this.pRECIOField = value;
            }
        }
        
        /// <comentarios/>
        public string DESCRIPCION {
            get {
                return this.dESCRIPCIONField;
            }
            set {
                this.dESCRIPCIONField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] IMAGEN {
            get {
                return this.iMAGENField;
            }
            set {
                this.iMAGENField = value;
            }
        }
        
        /// <comentarios/>
        public string NOM_TIPO_PRODUCTO {
            get {
                return this.nOM_TIPO_PRODUCTOField;
            }
            set {
                this.nOM_TIPO_PRODUCTOField = value;
            }
        }
        
        /// <comentarios/>
        public string NIT {
            get {
                return this.nITField;
            }
            set {
                this.nITField = value;
            }
        }
        
        /// <comentarios/>
        public string RAZON_SOCIAL {
            get {
                return this.rAZON_SOCIALField;
            }
            set {
                this.rAZON_SOCIALField = value;
            }
        }
        
        /// <comentarios/>
        public string SUCURSAL {
            get {
                return this.sUCURSALField;
            }
            set {
                this.sUCURSALField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void crearViewproductoCompletedEventHandler(object sender, crearViewproductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class crearViewproductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal crearViewproductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Viewproducto Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Viewproducto)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void editarViewproductoCompletedEventHandler(object sender, editarViewproductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class editarViewproductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal editarViewproductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void buscarPrimeroViewproductoCompletedEventHandler(object sender, buscarPrimeroViewproductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarPrimeroViewproductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarPrimeroViewproductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Viewproducto Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Viewproducto)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void buscarViewproductoCompletedEventHandler(object sender, buscarViewproductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarViewproductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarViewproductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Viewproducto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Viewproducto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void buscarPaginacionViewproductoCompletedEventHandler(object sender, buscarPaginacionViewproductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarPaginacionViewproductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarPaginacionViewproductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Viewproducto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Viewproducto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void listarViewproductoCompletedEventHandler(object sender, listarViewproductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarViewproductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarViewproductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Viewproducto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Viewproducto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void listarPaginacionViewproductoCompletedEventHandler(object sender, listarPaginacionViewproductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarPaginacionViewproductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarPaginacionViewproductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Viewproducto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Viewproducto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void contarBusquedaViewproductoCompletedEventHandler(object sender, contarBusquedaViewproductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class contarBusquedaViewproductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal contarBusquedaViewproductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void eliminarViewproductoCompletedEventHandler(object sender, eliminarViewproductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eliminarViewproductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eliminarViewproductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591