//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Controles.WS_ServiciosMunicipio {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiciosMunicipioSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Response))]
    public partial class ServiciosMunicipio : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private Autenticacion autenticacionValueField;
        
        private System.Threading.SendOrPostCallback crearMunicipioOperationCompleted;
        
        private System.Threading.SendOrPostCallback editarMunicipioOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarPrimeroMunicipioOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarMunicipioOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarPaginacionMunicipioOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarMunicipioOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarPaginacionMunicipioOperationCompleted;
        
        private System.Threading.SendOrPostCallback contarBusquedaMunicipioOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarMunicipioOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiciosMunicipio() {
            this.Url = global::Controles.Properties.Settings.Default.Controles_WS_ServiciosMunicipio_ServiciosMunicipio;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public Autenticacion AutenticacionValue {
            get {
                return this.autenticacionValueField;
            }
            set {
                this.autenticacionValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event crearMunicipioCompletedEventHandler crearMunicipioCompleted;
        
        /// <remarks/>
        public event editarMunicipioCompletedEventHandler editarMunicipioCompleted;
        
        /// <remarks/>
        public event buscarPrimeroMunicipioCompletedEventHandler buscarPrimeroMunicipioCompleted;
        
        /// <remarks/>
        public event buscarMunicipioCompletedEventHandler buscarMunicipioCompleted;
        
        /// <remarks/>
        public event buscarPaginacionMunicipioCompletedEventHandler buscarPaginacionMunicipioCompleted;
        
        /// <remarks/>
        public event listarMunicipioCompletedEventHandler listarMunicipioCompleted;
        
        /// <remarks/>
        public event listarPaginacionMunicipioCompletedEventHandler listarPaginacionMunicipioCompleted;
        
        /// <remarks/>
        public event contarBusquedaMunicipioCompletedEventHandler contarBusquedaMunicipioCompleted;
        
        /// <remarks/>
        public event eliminarMunicipioCompletedEventHandler eliminarMunicipioCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/crearMunicipio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MunicipioResponse crearMunicipio(Municipio obj) {
            object[] results = this.Invoke("crearMunicipio", new object[] {
                        obj});
            return ((MunicipioResponse)(results[0]));
        }
        
        /// <remarks/>
        public void crearMunicipioAsync(Municipio obj) {
            this.crearMunicipioAsync(obj, null);
        }
        
        /// <remarks/>
        public void crearMunicipioAsync(Municipio obj, object userState) {
            if ((this.crearMunicipioOperationCompleted == null)) {
                this.crearMunicipioOperationCompleted = new System.Threading.SendOrPostCallback(this.OncrearMunicipioOperationCompleted);
            }
            this.InvokeAsync("crearMunicipio", new object[] {
                        obj}, this.crearMunicipioOperationCompleted, userState);
        }
        
        private void OncrearMunicipioOperationCompleted(object arg) {
            if ((this.crearMunicipioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.crearMunicipioCompleted(this, new crearMunicipioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/editarMunicipio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MunicipioResponse editarMunicipio(Municipio obj) {
            object[] results = this.Invoke("editarMunicipio", new object[] {
                        obj});
            return ((MunicipioResponse)(results[0]));
        }
        
        /// <remarks/>
        public void editarMunicipioAsync(Municipio obj) {
            this.editarMunicipioAsync(obj, null);
        }
        
        /// <remarks/>
        public void editarMunicipioAsync(Municipio obj, object userState) {
            if ((this.editarMunicipioOperationCompleted == null)) {
                this.editarMunicipioOperationCompleted = new System.Threading.SendOrPostCallback(this.OneditarMunicipioOperationCompleted);
            }
            this.InvokeAsync("editarMunicipio", new object[] {
                        obj}, this.editarMunicipioOperationCompleted, userState);
        }
        
        private void OneditarMunicipioOperationCompleted(object arg) {
            if ((this.editarMunicipioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.editarMunicipioCompleted(this, new editarMunicipioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarPrimeroMunicipio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Municipio buscarPrimeroMunicipio(Municipio obj) {
            object[] results = this.Invoke("buscarPrimeroMunicipio", new object[] {
                        obj});
            return ((Municipio)(results[0]));
        }
        
        /// <remarks/>
        public void buscarPrimeroMunicipioAsync(Municipio obj) {
            this.buscarPrimeroMunicipioAsync(obj, null);
        }
        
        /// <remarks/>
        public void buscarPrimeroMunicipioAsync(Municipio obj, object userState) {
            if ((this.buscarPrimeroMunicipioOperationCompleted == null)) {
                this.buscarPrimeroMunicipioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarPrimeroMunicipioOperationCompleted);
            }
            this.InvokeAsync("buscarPrimeroMunicipio", new object[] {
                        obj}, this.buscarPrimeroMunicipioOperationCompleted, userState);
        }
        
        private void OnbuscarPrimeroMunicipioOperationCompleted(object arg) {
            if ((this.buscarPrimeroMunicipioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarPrimeroMunicipioCompleted(this, new buscarPrimeroMunicipioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarMunicipio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Municipio[] buscarMunicipio(Municipio obj) {
            object[] results = this.Invoke("buscarMunicipio", new object[] {
                        obj});
            return ((Municipio[])(results[0]));
        }
        
        /// <remarks/>
        public void buscarMunicipioAsync(Municipio obj) {
            this.buscarMunicipioAsync(obj, null);
        }
        
        /// <remarks/>
        public void buscarMunicipioAsync(Municipio obj, object userState) {
            if ((this.buscarMunicipioOperationCompleted == null)) {
                this.buscarMunicipioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarMunicipioOperationCompleted);
            }
            this.InvokeAsync("buscarMunicipio", new object[] {
                        obj}, this.buscarMunicipioOperationCompleted, userState);
        }
        
        private void OnbuscarMunicipioOperationCompleted(object arg) {
            if ((this.buscarMunicipioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarMunicipioCompleted(this, new buscarMunicipioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarPaginacionMunicipio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Municipio[] buscarPaginacionMunicipio(Municipio obj, int pag, int numReg) {
            object[] results = this.Invoke("buscarPaginacionMunicipio", new object[] {
                        obj,
                        pag,
                        numReg});
            return ((Municipio[])(results[0]));
        }
        
        /// <remarks/>
        public void buscarPaginacionMunicipioAsync(Municipio obj, int pag, int numReg) {
            this.buscarPaginacionMunicipioAsync(obj, pag, numReg, null);
        }
        
        /// <remarks/>
        public void buscarPaginacionMunicipioAsync(Municipio obj, int pag, int numReg, object userState) {
            if ((this.buscarPaginacionMunicipioOperationCompleted == null)) {
                this.buscarPaginacionMunicipioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarPaginacionMunicipioOperationCompleted);
            }
            this.InvokeAsync("buscarPaginacionMunicipio", new object[] {
                        obj,
                        pag,
                        numReg}, this.buscarPaginacionMunicipioOperationCompleted, userState);
        }
        
        private void OnbuscarPaginacionMunicipioOperationCompleted(object arg) {
            if ((this.buscarPaginacionMunicipioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarPaginacionMunicipioCompleted(this, new buscarPaginacionMunicipioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarMunicipio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Municipio[] listarMunicipio() {
            object[] results = this.Invoke("listarMunicipio", new object[0]);
            return ((Municipio[])(results[0]));
        }
        
        /// <remarks/>
        public void listarMunicipioAsync() {
            this.listarMunicipioAsync(null);
        }
        
        /// <remarks/>
        public void listarMunicipioAsync(object userState) {
            if ((this.listarMunicipioOperationCompleted == null)) {
                this.listarMunicipioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarMunicipioOperationCompleted);
            }
            this.InvokeAsync("listarMunicipio", new object[0], this.listarMunicipioOperationCompleted, userState);
        }
        
        private void OnlistarMunicipioOperationCompleted(object arg) {
            if ((this.listarMunicipioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarMunicipioCompleted(this, new listarMunicipioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarPaginacionMunicipio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Municipio[] listarPaginacionMunicipio(int pag, int numReg) {
            object[] results = this.Invoke("listarPaginacionMunicipio", new object[] {
                        pag,
                        numReg});
            return ((Municipio[])(results[0]));
        }
        
        /// <remarks/>
        public void listarPaginacionMunicipioAsync(int pag, int numReg) {
            this.listarPaginacionMunicipioAsync(pag, numReg, null);
        }
        
        /// <remarks/>
        public void listarPaginacionMunicipioAsync(int pag, int numReg, object userState) {
            if ((this.listarPaginacionMunicipioOperationCompleted == null)) {
                this.listarPaginacionMunicipioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarPaginacionMunicipioOperationCompleted);
            }
            this.InvokeAsync("listarPaginacionMunicipio", new object[] {
                        pag,
                        numReg}, this.listarPaginacionMunicipioOperationCompleted, userState);
        }
        
        private void OnlistarPaginacionMunicipioOperationCompleted(object arg) {
            if ((this.listarPaginacionMunicipioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarPaginacionMunicipioCompleted(this, new listarPaginacionMunicipioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/contarBusquedaMunicipio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int contarBusquedaMunicipio(Municipio obj) {
            object[] results = this.Invoke("contarBusquedaMunicipio", new object[] {
                        obj});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void contarBusquedaMunicipioAsync(Municipio obj) {
            this.contarBusquedaMunicipioAsync(obj, null);
        }
        
        /// <remarks/>
        public void contarBusquedaMunicipioAsync(Municipio obj, object userState) {
            if ((this.contarBusquedaMunicipioOperationCompleted == null)) {
                this.contarBusquedaMunicipioOperationCompleted = new System.Threading.SendOrPostCallback(this.OncontarBusquedaMunicipioOperationCompleted);
            }
            this.InvokeAsync("contarBusquedaMunicipio", new object[] {
                        obj}, this.contarBusquedaMunicipioOperationCompleted, userState);
        }
        
        private void OncontarBusquedaMunicipioOperationCompleted(object arg) {
            if ((this.contarBusquedaMunicipioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.contarBusquedaMunicipioCompleted(this, new contarBusquedaMunicipioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/eliminarMunicipio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MunicipioResponse eliminarMunicipio(Municipio obj) {
            object[] results = this.Invoke("eliminarMunicipio", new object[] {
                        obj});
            return ((MunicipioResponse)(results[0]));
        }
        
        /// <remarks/>
        public void eliminarMunicipioAsync(Municipio obj) {
            this.eliminarMunicipioAsync(obj, null);
        }
        
        /// <remarks/>
        public void eliminarMunicipioAsync(Municipio obj, object userState) {
            if ((this.eliminarMunicipioOperationCompleted == null)) {
                this.eliminarMunicipioOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarMunicipioOperationCompleted);
            }
            this.InvokeAsync("eliminarMunicipio", new object[] {
                        obj}, this.eliminarMunicipioOperationCompleted, userState);
        }
        
        private void OneliminarMunicipioOperationCompleted(object arg) {
            if ((this.eliminarMunicipioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarMunicipioCompleted(this, new eliminarMunicipioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class Autenticacion : System.Web.Services.Protocols.SoapHeader {
        
        private string usuarioField;
        
        private string contrasenaField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <comentarios/>
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <comentarios/>
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                this.contrasenaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MunicipioResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class Response {
        
        private bool correctoField;
        
        private string errorField;
        
        private string numeroField;
        
        /// <comentarios/>
        public bool correcto {
            get {
                return this.correctoField;
            }
            set {
                this.correctoField = value;
            }
        }
        
        /// <comentarios/>
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <comentarios/>
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MunicipioResponse : Response {
        
        private Municipio objetoField;
        
        /// <comentarios/>
        public Municipio objeto {
            get {
                return this.objetoField;
            }
            set {
                this.objetoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Municipio {
        
        private long iD_MUNICIPIOField;
        
        private long iD_DEPARTAMENTOField;
        
        private string nOM_MUNICIPIOField;
        
        /// <comentarios/>
        public long ID_MUNICIPIO {
            get {
                return this.iD_MUNICIPIOField;
            }
            set {
                this.iD_MUNICIPIOField = value;
            }
        }
        
        /// <comentarios/>
        public long ID_DEPARTAMENTO {
            get {
                return this.iD_DEPARTAMENTOField;
            }
            set {
                this.iD_DEPARTAMENTOField = value;
            }
        }
        
        /// <comentarios/>
        public string NOM_MUNICIPIO {
            get {
                return this.nOM_MUNICIPIOField;
            }
            set {
                this.nOM_MUNICIPIOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void crearMunicipioCompletedEventHandler(object sender, crearMunicipioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class crearMunicipioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal crearMunicipioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MunicipioResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MunicipioResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void editarMunicipioCompletedEventHandler(object sender, editarMunicipioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class editarMunicipioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal editarMunicipioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MunicipioResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MunicipioResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void buscarPrimeroMunicipioCompletedEventHandler(object sender, buscarPrimeroMunicipioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarPrimeroMunicipioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarPrimeroMunicipioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Municipio Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Municipio)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void buscarMunicipioCompletedEventHandler(object sender, buscarMunicipioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarMunicipioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarMunicipioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Municipio[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Municipio[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void buscarPaginacionMunicipioCompletedEventHandler(object sender, buscarPaginacionMunicipioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarPaginacionMunicipioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarPaginacionMunicipioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Municipio[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Municipio[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void listarMunicipioCompletedEventHandler(object sender, listarMunicipioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarMunicipioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarMunicipioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Municipio[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Municipio[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void listarPaginacionMunicipioCompletedEventHandler(object sender, listarPaginacionMunicipioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarPaginacionMunicipioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarPaginacionMunicipioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Municipio[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Municipio[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void contarBusquedaMunicipioCompletedEventHandler(object sender, contarBusquedaMunicipioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class contarBusquedaMunicipioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal contarBusquedaMunicipioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void eliminarMunicipioCompletedEventHandler(object sender, eliminarMunicipioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eliminarMunicipioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eliminarMunicipioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MunicipioResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MunicipioResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591