//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ClienteFiel.WS_ServiciosViewempresa {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiciosViewempresaSoap", Namespace="http://tempuri.org/")]
    public partial class ServiciosViewempresa : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private Autenticacion autenticacionValueField;
        
        private System.Threading.SendOrPostCallback crearViewempresaOperationCompleted;
        
        private System.Threading.SendOrPostCallback editarViewempresaOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarPrimeroViewempresaOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarViewempresaOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarPaginacionViewempresaOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarViewempresaOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarPaginacionViewempresaOperationCompleted;
        
        private System.Threading.SendOrPostCallback contarBusquedaViewempresaOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarViewempresaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiciosViewempresa() {
            this.Url = global::ClienteFiel.Properties.Settings.Default.ClienteFiel_WS_ServiciosViewempresa_ServiciosViewempresa;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public Autenticacion AutenticacionValue {
            get {
                return this.autenticacionValueField;
            }
            set {
                this.autenticacionValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event crearViewempresaCompletedEventHandler crearViewempresaCompleted;
        
        /// <remarks/>
        public event editarViewempresaCompletedEventHandler editarViewempresaCompleted;
        
        /// <remarks/>
        public event buscarPrimeroViewempresaCompletedEventHandler buscarPrimeroViewempresaCompleted;
        
        /// <remarks/>
        public event buscarViewempresaCompletedEventHandler buscarViewempresaCompleted;
        
        /// <remarks/>
        public event buscarPaginacionViewempresaCompletedEventHandler buscarPaginacionViewempresaCompleted;
        
        /// <remarks/>
        public event listarViewempresaCompletedEventHandler listarViewempresaCompleted;
        
        /// <remarks/>
        public event listarPaginacionViewempresaCompletedEventHandler listarPaginacionViewempresaCompleted;
        
        /// <remarks/>
        public event contarBusquedaViewempresaCompletedEventHandler contarBusquedaViewempresaCompleted;
        
        /// <remarks/>
        public event eliminarViewempresaCompletedEventHandler eliminarViewempresaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/crearViewempresa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Viewempresa crearViewempresa(Viewempresa obj) {
            object[] results = this.Invoke("crearViewempresa", new object[] {
                        obj});
            return ((Viewempresa)(results[0]));
        }
        
        /// <remarks/>
        public void crearViewempresaAsync(Viewempresa obj) {
            this.crearViewempresaAsync(obj, null);
        }
        
        /// <remarks/>
        public void crearViewempresaAsync(Viewempresa obj, object userState) {
            if ((this.crearViewempresaOperationCompleted == null)) {
                this.crearViewempresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OncrearViewempresaOperationCompleted);
            }
            this.InvokeAsync("crearViewempresa", new object[] {
                        obj}, this.crearViewempresaOperationCompleted, userState);
        }
        
        private void OncrearViewempresaOperationCompleted(object arg) {
            if ((this.crearViewempresaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.crearViewempresaCompleted(this, new crearViewempresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/editarViewempresa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool editarViewempresa(Viewempresa obj) {
            object[] results = this.Invoke("editarViewempresa", new object[] {
                        obj});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void editarViewempresaAsync(Viewempresa obj) {
            this.editarViewempresaAsync(obj, null);
        }
        
        /// <remarks/>
        public void editarViewempresaAsync(Viewempresa obj, object userState) {
            if ((this.editarViewempresaOperationCompleted == null)) {
                this.editarViewempresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OneditarViewempresaOperationCompleted);
            }
            this.InvokeAsync("editarViewempresa", new object[] {
                        obj}, this.editarViewempresaOperationCompleted, userState);
        }
        
        private void OneditarViewempresaOperationCompleted(object arg) {
            if ((this.editarViewempresaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.editarViewempresaCompleted(this, new editarViewempresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarPrimeroViewempresa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Viewempresa buscarPrimeroViewempresa(Viewempresa obj) {
            object[] results = this.Invoke("buscarPrimeroViewempresa", new object[] {
                        obj});
            return ((Viewempresa)(results[0]));
        }
        
        /// <remarks/>
        public void buscarPrimeroViewempresaAsync(Viewempresa obj) {
            this.buscarPrimeroViewempresaAsync(obj, null);
        }
        
        /// <remarks/>
        public void buscarPrimeroViewempresaAsync(Viewempresa obj, object userState) {
            if ((this.buscarPrimeroViewempresaOperationCompleted == null)) {
                this.buscarPrimeroViewempresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarPrimeroViewempresaOperationCompleted);
            }
            this.InvokeAsync("buscarPrimeroViewempresa", new object[] {
                        obj}, this.buscarPrimeroViewempresaOperationCompleted, userState);
        }
        
        private void OnbuscarPrimeroViewempresaOperationCompleted(object arg) {
            if ((this.buscarPrimeroViewempresaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarPrimeroViewempresaCompleted(this, new buscarPrimeroViewempresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarViewempresa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Viewempresa[] buscarViewempresa(Viewempresa obj) {
            object[] results = this.Invoke("buscarViewempresa", new object[] {
                        obj});
            return ((Viewempresa[])(results[0]));
        }
        
        /// <remarks/>
        public void buscarViewempresaAsync(Viewempresa obj) {
            this.buscarViewempresaAsync(obj, null);
        }
        
        /// <remarks/>
        public void buscarViewempresaAsync(Viewempresa obj, object userState) {
            if ((this.buscarViewempresaOperationCompleted == null)) {
                this.buscarViewempresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarViewempresaOperationCompleted);
            }
            this.InvokeAsync("buscarViewempresa", new object[] {
                        obj}, this.buscarViewempresaOperationCompleted, userState);
        }
        
        private void OnbuscarViewempresaOperationCompleted(object arg) {
            if ((this.buscarViewempresaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarViewempresaCompleted(this, new buscarViewempresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarPaginacionViewempresa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Viewempresa[] buscarPaginacionViewempresa(Viewempresa obj, int pag, int numReg) {
            object[] results = this.Invoke("buscarPaginacionViewempresa", new object[] {
                        obj,
                        pag,
                        numReg});
            return ((Viewempresa[])(results[0]));
        }
        
        /// <remarks/>
        public void buscarPaginacionViewempresaAsync(Viewempresa obj, int pag, int numReg) {
            this.buscarPaginacionViewempresaAsync(obj, pag, numReg, null);
        }
        
        /// <remarks/>
        public void buscarPaginacionViewempresaAsync(Viewempresa obj, int pag, int numReg, object userState) {
            if ((this.buscarPaginacionViewempresaOperationCompleted == null)) {
                this.buscarPaginacionViewempresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarPaginacionViewempresaOperationCompleted);
            }
            this.InvokeAsync("buscarPaginacionViewempresa", new object[] {
                        obj,
                        pag,
                        numReg}, this.buscarPaginacionViewempresaOperationCompleted, userState);
        }
        
        private void OnbuscarPaginacionViewempresaOperationCompleted(object arg) {
            if ((this.buscarPaginacionViewempresaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarPaginacionViewempresaCompleted(this, new buscarPaginacionViewempresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarViewempresa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Viewempresa[] listarViewempresa() {
            object[] results = this.Invoke("listarViewempresa", new object[0]);
            return ((Viewempresa[])(results[0]));
        }
        
        /// <remarks/>
        public void listarViewempresaAsync() {
            this.listarViewempresaAsync(null);
        }
        
        /// <remarks/>
        public void listarViewempresaAsync(object userState) {
            if ((this.listarViewempresaOperationCompleted == null)) {
                this.listarViewempresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarViewempresaOperationCompleted);
            }
            this.InvokeAsync("listarViewempresa", new object[0], this.listarViewempresaOperationCompleted, userState);
        }
        
        private void OnlistarViewempresaOperationCompleted(object arg) {
            if ((this.listarViewempresaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarViewempresaCompleted(this, new listarViewempresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarPaginacionViewempresa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Viewempresa[] listarPaginacionViewempresa(int pag, int numReg) {
            object[] results = this.Invoke("listarPaginacionViewempresa", new object[] {
                        pag,
                        numReg});
            return ((Viewempresa[])(results[0]));
        }
        
        /// <remarks/>
        public void listarPaginacionViewempresaAsync(int pag, int numReg) {
            this.listarPaginacionViewempresaAsync(pag, numReg, null);
        }
        
        /// <remarks/>
        public void listarPaginacionViewempresaAsync(int pag, int numReg, object userState) {
            if ((this.listarPaginacionViewempresaOperationCompleted == null)) {
                this.listarPaginacionViewempresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarPaginacionViewempresaOperationCompleted);
            }
            this.InvokeAsync("listarPaginacionViewempresa", new object[] {
                        pag,
                        numReg}, this.listarPaginacionViewempresaOperationCompleted, userState);
        }
        
        private void OnlistarPaginacionViewempresaOperationCompleted(object arg) {
            if ((this.listarPaginacionViewempresaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarPaginacionViewempresaCompleted(this, new listarPaginacionViewempresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/contarBusquedaViewempresa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int contarBusquedaViewempresa(Viewempresa obj) {
            object[] results = this.Invoke("contarBusquedaViewempresa", new object[] {
                        obj});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void contarBusquedaViewempresaAsync(Viewempresa obj) {
            this.contarBusquedaViewempresaAsync(obj, null);
        }
        
        /// <remarks/>
        public void contarBusquedaViewempresaAsync(Viewempresa obj, object userState) {
            if ((this.contarBusquedaViewempresaOperationCompleted == null)) {
                this.contarBusquedaViewempresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OncontarBusquedaViewempresaOperationCompleted);
            }
            this.InvokeAsync("contarBusquedaViewempresa", new object[] {
                        obj}, this.contarBusquedaViewempresaOperationCompleted, userState);
        }
        
        private void OncontarBusquedaViewempresaOperationCompleted(object arg) {
            if ((this.contarBusquedaViewempresaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.contarBusquedaViewempresaCompleted(this, new contarBusquedaViewempresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/eliminarViewempresa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool eliminarViewempresa(Viewempresa obj) {
            object[] results = this.Invoke("eliminarViewempresa", new object[] {
                        obj});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void eliminarViewempresaAsync(Viewempresa obj) {
            this.eliminarViewempresaAsync(obj, null);
        }
        
        /// <remarks/>
        public void eliminarViewempresaAsync(Viewempresa obj, object userState) {
            if ((this.eliminarViewempresaOperationCompleted == null)) {
                this.eliminarViewempresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarViewempresaOperationCompleted);
            }
            this.InvokeAsync("eliminarViewempresa", new object[] {
                        obj}, this.eliminarViewempresaOperationCompleted, userState);
        }
        
        private void OneliminarViewempresaOperationCompleted(object arg) {
            if ((this.eliminarViewempresaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarViewempresaCompleted(this, new eliminarViewempresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class Autenticacion : System.Web.Services.Protocols.SoapHeader {
        
        private string usuarioField;
        
        private string contrasenaField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <comentarios/>
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <comentarios/>
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                this.contrasenaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Viewempresa {
        
        private long iD_EMPRESAField;
        
        private long iD_MUNICIPIOField;
        
        private long iD_IMAGENField;
        
        private string nITField;
        
        private string rAZON_SOCIALField;
        
        private string dIRECCION_CLIENTEField;
        
        private string tELEFONOField;
        
        private string sLOGANField;
        
        private string lATITUDField;
        
        private string lONGITUDField;
        
        private string sUCURSALField;
        
        private string nOM_MUNICIPIOField;
        
        private byte[] iMAGENField;
        
        /// <comentarios/>
        public long ID_EMPRESA {
            get {
                return this.iD_EMPRESAField;
            }
            set {
                this.iD_EMPRESAField = value;
            }
        }
        
        /// <comentarios/>
        public long ID_MUNICIPIO {
            get {
                return this.iD_MUNICIPIOField;
            }
            set {
                this.iD_MUNICIPIOField = value;
            }
        }
        
        /// <comentarios/>
        public long ID_IMAGEN {
            get {
                return this.iD_IMAGENField;
            }
            set {
                this.iD_IMAGENField = value;
            }
        }
        
        /// <comentarios/>
        public string NIT {
            get {
                return this.nITField;
            }
            set {
                this.nITField = value;
            }
        }
        
        /// <comentarios/>
        public string RAZON_SOCIAL {
            get {
                return this.rAZON_SOCIALField;
            }
            set {
                this.rAZON_SOCIALField = value;
            }
        }
        
        /// <comentarios/>
        public string DIRECCION_CLIENTE {
            get {
                return this.dIRECCION_CLIENTEField;
            }
            set {
                this.dIRECCION_CLIENTEField = value;
            }
        }
        
        /// <comentarios/>
        public string TELEFONO {
            get {
                return this.tELEFONOField;
            }
            set {
                this.tELEFONOField = value;
            }
        }
        
        /// <comentarios/>
        public string SLOGAN {
            get {
                return this.sLOGANField;
            }
            set {
                this.sLOGANField = value;
            }
        }
        
        /// <comentarios/>
        public string LATITUD {
            get {
                return this.lATITUDField;
            }
            set {
                this.lATITUDField = value;
            }
        }
        
        /// <comentarios/>
        public string LONGITUD {
            get {
                return this.lONGITUDField;
            }
            set {
                this.lONGITUDField = value;
            }
        }
        
        /// <comentarios/>
        public string SUCURSAL {
            get {
                return this.sUCURSALField;
            }
            set {
                this.sUCURSALField = value;
            }
        }
        
        /// <comentarios/>
        public string NOM_MUNICIPIO {
            get {
                return this.nOM_MUNICIPIOField;
            }
            set {
                this.nOM_MUNICIPIOField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] IMAGEN {
            get {
                return this.iMAGENField;
            }
            set {
                this.iMAGENField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void crearViewempresaCompletedEventHandler(object sender, crearViewempresaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class crearViewempresaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal crearViewempresaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Viewempresa Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Viewempresa)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void editarViewempresaCompletedEventHandler(object sender, editarViewempresaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class editarViewempresaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal editarViewempresaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void buscarPrimeroViewempresaCompletedEventHandler(object sender, buscarPrimeroViewempresaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarPrimeroViewempresaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarPrimeroViewempresaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Viewempresa Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Viewempresa)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void buscarViewempresaCompletedEventHandler(object sender, buscarViewempresaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarViewempresaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarViewempresaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Viewempresa[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Viewempresa[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void buscarPaginacionViewempresaCompletedEventHandler(object sender, buscarPaginacionViewempresaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarPaginacionViewempresaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarPaginacionViewempresaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Viewempresa[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Viewempresa[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void listarViewempresaCompletedEventHandler(object sender, listarViewempresaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarViewempresaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarViewempresaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Viewempresa[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Viewempresa[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void listarPaginacionViewempresaCompletedEventHandler(object sender, listarPaginacionViewempresaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarPaginacionViewempresaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarPaginacionViewempresaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Viewempresa[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Viewempresa[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void contarBusquedaViewempresaCompletedEventHandler(object sender, contarBusquedaViewempresaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class contarBusquedaViewempresaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal contarBusquedaViewempresaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void eliminarViewempresaCompletedEventHandler(object sender, eliminarViewempresaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eliminarViewempresaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eliminarViewempresaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591