//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ClienteFiel.WS_ServiciosProducto {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiciosProductoSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Response))]
    public partial class ServiciosProducto : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private Autenticacion autenticacionValueField;
        
        private System.Threading.SendOrPostCallback crearProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback editarProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarPrimeroProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarPaginacionProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarPaginacionProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback contarBusquedaProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarProductoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiciosProducto() {
            this.Url = global::ClienteFiel.Properties.Settings.Default.ClienteFiel_WS_ServiciosProducto_ServiciosProducto;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public Autenticacion AutenticacionValue {
            get {
                return this.autenticacionValueField;
            }
            set {
                this.autenticacionValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event crearProductoCompletedEventHandler crearProductoCompleted;
        
        /// <remarks/>
        public event editarProductoCompletedEventHandler editarProductoCompleted;
        
        /// <remarks/>
        public event buscarPrimeroProductoCompletedEventHandler buscarPrimeroProductoCompleted;
        
        /// <remarks/>
        public event buscarProductoCompletedEventHandler buscarProductoCompleted;
        
        /// <remarks/>
        public event buscarPaginacionProductoCompletedEventHandler buscarPaginacionProductoCompleted;
        
        /// <remarks/>
        public event listarProductoCompletedEventHandler listarProductoCompleted;
        
        /// <remarks/>
        public event listarPaginacionProductoCompletedEventHandler listarPaginacionProductoCompleted;
        
        /// <remarks/>
        public event contarBusquedaProductoCompletedEventHandler contarBusquedaProductoCompleted;
        
        /// <remarks/>
        public event eliminarProductoCompletedEventHandler eliminarProductoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/crearProducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductoResponse crearProducto(Producto obj) {
            object[] results = this.Invoke("crearProducto", new object[] {
                        obj});
            return ((ProductoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void crearProductoAsync(Producto obj) {
            this.crearProductoAsync(obj, null);
        }
        
        /// <remarks/>
        public void crearProductoAsync(Producto obj, object userState) {
            if ((this.crearProductoOperationCompleted == null)) {
                this.crearProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OncrearProductoOperationCompleted);
            }
            this.InvokeAsync("crearProducto", new object[] {
                        obj}, this.crearProductoOperationCompleted, userState);
        }
        
        private void OncrearProductoOperationCompleted(object arg) {
            if ((this.crearProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.crearProductoCompleted(this, new crearProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/editarProducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductoResponse editarProducto(Producto obj) {
            object[] results = this.Invoke("editarProducto", new object[] {
                        obj});
            return ((ProductoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void editarProductoAsync(Producto obj) {
            this.editarProductoAsync(obj, null);
        }
        
        /// <remarks/>
        public void editarProductoAsync(Producto obj, object userState) {
            if ((this.editarProductoOperationCompleted == null)) {
                this.editarProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OneditarProductoOperationCompleted);
            }
            this.InvokeAsync("editarProducto", new object[] {
                        obj}, this.editarProductoOperationCompleted, userState);
        }
        
        private void OneditarProductoOperationCompleted(object arg) {
            if ((this.editarProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.editarProductoCompleted(this, new editarProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarPrimeroProducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Producto buscarPrimeroProducto(Producto obj) {
            object[] results = this.Invoke("buscarPrimeroProducto", new object[] {
                        obj});
            return ((Producto)(results[0]));
        }
        
        /// <remarks/>
        public void buscarPrimeroProductoAsync(Producto obj) {
            this.buscarPrimeroProductoAsync(obj, null);
        }
        
        /// <remarks/>
        public void buscarPrimeroProductoAsync(Producto obj, object userState) {
            if ((this.buscarPrimeroProductoOperationCompleted == null)) {
                this.buscarPrimeroProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarPrimeroProductoOperationCompleted);
            }
            this.InvokeAsync("buscarPrimeroProducto", new object[] {
                        obj}, this.buscarPrimeroProductoOperationCompleted, userState);
        }
        
        private void OnbuscarPrimeroProductoOperationCompleted(object arg) {
            if ((this.buscarPrimeroProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarPrimeroProductoCompleted(this, new buscarPrimeroProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarProducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Producto[] buscarProducto(Producto obj) {
            object[] results = this.Invoke("buscarProducto", new object[] {
                        obj});
            return ((Producto[])(results[0]));
        }
        
        /// <remarks/>
        public void buscarProductoAsync(Producto obj) {
            this.buscarProductoAsync(obj, null);
        }
        
        /// <remarks/>
        public void buscarProductoAsync(Producto obj, object userState) {
            if ((this.buscarProductoOperationCompleted == null)) {
                this.buscarProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarProductoOperationCompleted);
            }
            this.InvokeAsync("buscarProducto", new object[] {
                        obj}, this.buscarProductoOperationCompleted, userState);
        }
        
        private void OnbuscarProductoOperationCompleted(object arg) {
            if ((this.buscarProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarProductoCompleted(this, new buscarProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarPaginacionProducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Producto[] buscarPaginacionProducto(Producto obj, int pag, int numReg) {
            object[] results = this.Invoke("buscarPaginacionProducto", new object[] {
                        obj,
                        pag,
                        numReg});
            return ((Producto[])(results[0]));
        }
        
        /// <remarks/>
        public void buscarPaginacionProductoAsync(Producto obj, int pag, int numReg) {
            this.buscarPaginacionProductoAsync(obj, pag, numReg, null);
        }
        
        /// <remarks/>
        public void buscarPaginacionProductoAsync(Producto obj, int pag, int numReg, object userState) {
            if ((this.buscarPaginacionProductoOperationCompleted == null)) {
                this.buscarPaginacionProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarPaginacionProductoOperationCompleted);
            }
            this.InvokeAsync("buscarPaginacionProducto", new object[] {
                        obj,
                        pag,
                        numReg}, this.buscarPaginacionProductoOperationCompleted, userState);
        }
        
        private void OnbuscarPaginacionProductoOperationCompleted(object arg) {
            if ((this.buscarPaginacionProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarPaginacionProductoCompleted(this, new buscarPaginacionProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarProducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Producto[] listarProducto() {
            object[] results = this.Invoke("listarProducto", new object[0]);
            return ((Producto[])(results[0]));
        }
        
        /// <remarks/>
        public void listarProductoAsync() {
            this.listarProductoAsync(null);
        }
        
        /// <remarks/>
        public void listarProductoAsync(object userState) {
            if ((this.listarProductoOperationCompleted == null)) {
                this.listarProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarProductoOperationCompleted);
            }
            this.InvokeAsync("listarProducto", new object[0], this.listarProductoOperationCompleted, userState);
        }
        
        private void OnlistarProductoOperationCompleted(object arg) {
            if ((this.listarProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarProductoCompleted(this, new listarProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarPaginacionProducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Producto[] listarPaginacionProducto(int pag, int numReg) {
            object[] results = this.Invoke("listarPaginacionProducto", new object[] {
                        pag,
                        numReg});
            return ((Producto[])(results[0]));
        }
        
        /// <remarks/>
        public void listarPaginacionProductoAsync(int pag, int numReg) {
            this.listarPaginacionProductoAsync(pag, numReg, null);
        }
        
        /// <remarks/>
        public void listarPaginacionProductoAsync(int pag, int numReg, object userState) {
            if ((this.listarPaginacionProductoOperationCompleted == null)) {
                this.listarPaginacionProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarPaginacionProductoOperationCompleted);
            }
            this.InvokeAsync("listarPaginacionProducto", new object[] {
                        pag,
                        numReg}, this.listarPaginacionProductoOperationCompleted, userState);
        }
        
        private void OnlistarPaginacionProductoOperationCompleted(object arg) {
            if ((this.listarPaginacionProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarPaginacionProductoCompleted(this, new listarPaginacionProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/contarBusquedaProducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int contarBusquedaProducto(Producto obj) {
            object[] results = this.Invoke("contarBusquedaProducto", new object[] {
                        obj});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void contarBusquedaProductoAsync(Producto obj) {
            this.contarBusquedaProductoAsync(obj, null);
        }
        
        /// <remarks/>
        public void contarBusquedaProductoAsync(Producto obj, object userState) {
            if ((this.contarBusquedaProductoOperationCompleted == null)) {
                this.contarBusquedaProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OncontarBusquedaProductoOperationCompleted);
            }
            this.InvokeAsync("contarBusquedaProducto", new object[] {
                        obj}, this.contarBusquedaProductoOperationCompleted, userState);
        }
        
        private void OncontarBusquedaProductoOperationCompleted(object arg) {
            if ((this.contarBusquedaProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.contarBusquedaProductoCompleted(this, new contarBusquedaProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/eliminarProducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductoResponse eliminarProducto(Producto obj) {
            object[] results = this.Invoke("eliminarProducto", new object[] {
                        obj});
            return ((ProductoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void eliminarProductoAsync(Producto obj) {
            this.eliminarProductoAsync(obj, null);
        }
        
        /// <remarks/>
        public void eliminarProductoAsync(Producto obj, object userState) {
            if ((this.eliminarProductoOperationCompleted == null)) {
                this.eliminarProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarProductoOperationCompleted);
            }
            this.InvokeAsync("eliminarProducto", new object[] {
                        obj}, this.eliminarProductoOperationCompleted, userState);
        }
        
        private void OneliminarProductoOperationCompleted(object arg) {
            if ((this.eliminarProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarProductoCompleted(this, new eliminarProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class Autenticacion : System.Web.Services.Protocols.SoapHeader {
        
        private string usuarioField;
        
        private string contrasenaField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <comentarios/>
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <comentarios/>
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                this.contrasenaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductoResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class Response {
        
        private bool correctoField;
        
        private string errorField;
        
        private string numeroField;
        
        /// <comentarios/>
        public bool correcto {
            get {
                return this.correctoField;
            }
            set {
                this.correctoField = value;
            }
        }
        
        /// <comentarios/>
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <comentarios/>
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductoResponse : Response {
        
        private Producto objetoField;
        
        /// <comentarios/>
        public Producto objeto {
            get {
                return this.objetoField;
            }
            set {
                this.objetoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Producto {
        
        private long iD_PRODUCTOField;
        
        private long iD_IMAGENField;
        
        private long iD_TIPO_PRODUCTOField;
        
        private long iD_EMPRESAField;
        
        private string nOM_PRODUCTOField;
        
        private long pRECIOField;
        
        private string dESCRIPCIONField;
        
        /// <comentarios/>
        public long ID_PRODUCTO {
            get {
                return this.iD_PRODUCTOField;
            }
            set {
                this.iD_PRODUCTOField = value;
            }
        }
        
        /// <comentarios/>
        public long ID_IMAGEN {
            get {
                return this.iD_IMAGENField;
            }
            set {
                this.iD_IMAGENField = value;
            }
        }
        
        /// <comentarios/>
        public long ID_TIPO_PRODUCTO {
            get {
                return this.iD_TIPO_PRODUCTOField;
            }
            set {
                this.iD_TIPO_PRODUCTOField = value;
            }
        }
        
        /// <comentarios/>
        public long ID_EMPRESA {
            get {
                return this.iD_EMPRESAField;
            }
            set {
                this.iD_EMPRESAField = value;
            }
        }
        
        /// <comentarios/>
        public string NOM_PRODUCTO {
            get {
                return this.nOM_PRODUCTOField;
            }
            set {
                this.nOM_PRODUCTOField = value;
            }
        }
        
        /// <comentarios/>
        public long PRECIO {
            get {
                return this.pRECIOField;
            }
            set {
                this.pRECIOField = value;
            }
        }
        
        /// <comentarios/>
        public string DESCRIPCION {
            get {
                return this.dESCRIPCIONField;
            }
            set {
                this.dESCRIPCIONField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void crearProductoCompletedEventHandler(object sender, crearProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class crearProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal crearProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductoResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void editarProductoCompletedEventHandler(object sender, editarProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class editarProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal editarProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductoResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void buscarPrimeroProductoCompletedEventHandler(object sender, buscarPrimeroProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarPrimeroProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarPrimeroProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Producto Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Producto)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void buscarProductoCompletedEventHandler(object sender, buscarProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Producto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Producto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void buscarPaginacionProductoCompletedEventHandler(object sender, buscarPaginacionProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarPaginacionProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarPaginacionProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Producto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Producto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void listarProductoCompletedEventHandler(object sender, listarProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Producto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Producto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void listarPaginacionProductoCompletedEventHandler(object sender, listarPaginacionProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarPaginacionProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarPaginacionProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Producto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Producto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void contarBusquedaProductoCompletedEventHandler(object sender, contarBusquedaProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class contarBusquedaProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal contarBusquedaProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void eliminarProductoCompletedEventHandler(object sender, eliminarProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eliminarProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eliminarProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductoResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591