//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ClienteFiel.WS_ServiciosDepartamento {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiciosDepartamentoSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Response))]
    public partial class ServiciosDepartamento : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private Autenticacion autenticacionValueField;
        
        private System.Threading.SendOrPostCallback crearDepartamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback editarDepartamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarPrimeroDepartamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarDepartamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarPaginacionDepartamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarDepartamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarPaginacionDepartamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback contarBusquedaDepartamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarDepartamentoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiciosDepartamento() {
            this.Url = global::ClienteFiel.Properties.Settings.Default.ClienteFiel_WS_ServiciosDepartamento_ServiciosDepartamento;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public Autenticacion AutenticacionValue {
            get {
                return this.autenticacionValueField;
            }
            set {
                this.autenticacionValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event crearDepartamentoCompletedEventHandler crearDepartamentoCompleted;
        
        /// <remarks/>
        public event editarDepartamentoCompletedEventHandler editarDepartamentoCompleted;
        
        /// <remarks/>
        public event buscarPrimeroDepartamentoCompletedEventHandler buscarPrimeroDepartamentoCompleted;
        
        /// <remarks/>
        public event buscarDepartamentoCompletedEventHandler buscarDepartamentoCompleted;
        
        /// <remarks/>
        public event buscarPaginacionDepartamentoCompletedEventHandler buscarPaginacionDepartamentoCompleted;
        
        /// <remarks/>
        public event listarDepartamentoCompletedEventHandler listarDepartamentoCompleted;
        
        /// <remarks/>
        public event listarPaginacionDepartamentoCompletedEventHandler listarPaginacionDepartamentoCompleted;
        
        /// <remarks/>
        public event contarBusquedaDepartamentoCompletedEventHandler contarBusquedaDepartamentoCompleted;
        
        /// <remarks/>
        public event eliminarDepartamentoCompletedEventHandler eliminarDepartamentoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/crearDepartamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DepartamentoResponse crearDepartamento(Departamento obj) {
            object[] results = this.Invoke("crearDepartamento", new object[] {
                        obj});
            return ((DepartamentoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void crearDepartamentoAsync(Departamento obj) {
            this.crearDepartamentoAsync(obj, null);
        }
        
        /// <remarks/>
        public void crearDepartamentoAsync(Departamento obj, object userState) {
            if ((this.crearDepartamentoOperationCompleted == null)) {
                this.crearDepartamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OncrearDepartamentoOperationCompleted);
            }
            this.InvokeAsync("crearDepartamento", new object[] {
                        obj}, this.crearDepartamentoOperationCompleted, userState);
        }
        
        private void OncrearDepartamentoOperationCompleted(object arg) {
            if ((this.crearDepartamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.crearDepartamentoCompleted(this, new crearDepartamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/editarDepartamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DepartamentoResponse editarDepartamento(Departamento obj) {
            object[] results = this.Invoke("editarDepartamento", new object[] {
                        obj});
            return ((DepartamentoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void editarDepartamentoAsync(Departamento obj) {
            this.editarDepartamentoAsync(obj, null);
        }
        
        /// <remarks/>
        public void editarDepartamentoAsync(Departamento obj, object userState) {
            if ((this.editarDepartamentoOperationCompleted == null)) {
                this.editarDepartamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OneditarDepartamentoOperationCompleted);
            }
            this.InvokeAsync("editarDepartamento", new object[] {
                        obj}, this.editarDepartamentoOperationCompleted, userState);
        }
        
        private void OneditarDepartamentoOperationCompleted(object arg) {
            if ((this.editarDepartamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.editarDepartamentoCompleted(this, new editarDepartamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarPrimeroDepartamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Departamento buscarPrimeroDepartamento(Departamento obj) {
            object[] results = this.Invoke("buscarPrimeroDepartamento", new object[] {
                        obj});
            return ((Departamento)(results[0]));
        }
        
        /// <remarks/>
        public void buscarPrimeroDepartamentoAsync(Departamento obj) {
            this.buscarPrimeroDepartamentoAsync(obj, null);
        }
        
        /// <remarks/>
        public void buscarPrimeroDepartamentoAsync(Departamento obj, object userState) {
            if ((this.buscarPrimeroDepartamentoOperationCompleted == null)) {
                this.buscarPrimeroDepartamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarPrimeroDepartamentoOperationCompleted);
            }
            this.InvokeAsync("buscarPrimeroDepartamento", new object[] {
                        obj}, this.buscarPrimeroDepartamentoOperationCompleted, userState);
        }
        
        private void OnbuscarPrimeroDepartamentoOperationCompleted(object arg) {
            if ((this.buscarPrimeroDepartamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarPrimeroDepartamentoCompleted(this, new buscarPrimeroDepartamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarDepartamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Departamento[] buscarDepartamento(Departamento obj) {
            object[] results = this.Invoke("buscarDepartamento", new object[] {
                        obj});
            return ((Departamento[])(results[0]));
        }
        
        /// <remarks/>
        public void buscarDepartamentoAsync(Departamento obj) {
            this.buscarDepartamentoAsync(obj, null);
        }
        
        /// <remarks/>
        public void buscarDepartamentoAsync(Departamento obj, object userState) {
            if ((this.buscarDepartamentoOperationCompleted == null)) {
                this.buscarDepartamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarDepartamentoOperationCompleted);
            }
            this.InvokeAsync("buscarDepartamento", new object[] {
                        obj}, this.buscarDepartamentoOperationCompleted, userState);
        }
        
        private void OnbuscarDepartamentoOperationCompleted(object arg) {
            if ((this.buscarDepartamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarDepartamentoCompleted(this, new buscarDepartamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarPaginacionDepartamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Departamento[] buscarPaginacionDepartamento(Departamento obj, int pag, int numReg) {
            object[] results = this.Invoke("buscarPaginacionDepartamento", new object[] {
                        obj,
                        pag,
                        numReg});
            return ((Departamento[])(results[0]));
        }
        
        /// <remarks/>
        public void buscarPaginacionDepartamentoAsync(Departamento obj, int pag, int numReg) {
            this.buscarPaginacionDepartamentoAsync(obj, pag, numReg, null);
        }
        
        /// <remarks/>
        public void buscarPaginacionDepartamentoAsync(Departamento obj, int pag, int numReg, object userState) {
            if ((this.buscarPaginacionDepartamentoOperationCompleted == null)) {
                this.buscarPaginacionDepartamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarPaginacionDepartamentoOperationCompleted);
            }
            this.InvokeAsync("buscarPaginacionDepartamento", new object[] {
                        obj,
                        pag,
                        numReg}, this.buscarPaginacionDepartamentoOperationCompleted, userState);
        }
        
        private void OnbuscarPaginacionDepartamentoOperationCompleted(object arg) {
            if ((this.buscarPaginacionDepartamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarPaginacionDepartamentoCompleted(this, new buscarPaginacionDepartamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarDepartamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Departamento[] listarDepartamento() {
            object[] results = this.Invoke("listarDepartamento", new object[0]);
            return ((Departamento[])(results[0]));
        }
        
        /// <remarks/>
        public void listarDepartamentoAsync() {
            this.listarDepartamentoAsync(null);
        }
        
        /// <remarks/>
        public void listarDepartamentoAsync(object userState) {
            if ((this.listarDepartamentoOperationCompleted == null)) {
                this.listarDepartamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarDepartamentoOperationCompleted);
            }
            this.InvokeAsync("listarDepartamento", new object[0], this.listarDepartamentoOperationCompleted, userState);
        }
        
        private void OnlistarDepartamentoOperationCompleted(object arg) {
            if ((this.listarDepartamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarDepartamentoCompleted(this, new listarDepartamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarPaginacionDepartamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Departamento[] listarPaginacionDepartamento(int pag, int numReg) {
            object[] results = this.Invoke("listarPaginacionDepartamento", new object[] {
                        pag,
                        numReg});
            return ((Departamento[])(results[0]));
        }
        
        /// <remarks/>
        public void listarPaginacionDepartamentoAsync(int pag, int numReg) {
            this.listarPaginacionDepartamentoAsync(pag, numReg, null);
        }
        
        /// <remarks/>
        public void listarPaginacionDepartamentoAsync(int pag, int numReg, object userState) {
            if ((this.listarPaginacionDepartamentoOperationCompleted == null)) {
                this.listarPaginacionDepartamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarPaginacionDepartamentoOperationCompleted);
            }
            this.InvokeAsync("listarPaginacionDepartamento", new object[] {
                        pag,
                        numReg}, this.listarPaginacionDepartamentoOperationCompleted, userState);
        }
        
        private void OnlistarPaginacionDepartamentoOperationCompleted(object arg) {
            if ((this.listarPaginacionDepartamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarPaginacionDepartamentoCompleted(this, new listarPaginacionDepartamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/contarBusquedaDepartamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int contarBusquedaDepartamento(Departamento obj) {
            object[] results = this.Invoke("contarBusquedaDepartamento", new object[] {
                        obj});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void contarBusquedaDepartamentoAsync(Departamento obj) {
            this.contarBusquedaDepartamentoAsync(obj, null);
        }
        
        /// <remarks/>
        public void contarBusquedaDepartamentoAsync(Departamento obj, object userState) {
            if ((this.contarBusquedaDepartamentoOperationCompleted == null)) {
                this.contarBusquedaDepartamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OncontarBusquedaDepartamentoOperationCompleted);
            }
            this.InvokeAsync("contarBusquedaDepartamento", new object[] {
                        obj}, this.contarBusquedaDepartamentoOperationCompleted, userState);
        }
        
        private void OncontarBusquedaDepartamentoOperationCompleted(object arg) {
            if ((this.contarBusquedaDepartamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.contarBusquedaDepartamentoCompleted(this, new contarBusquedaDepartamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AutenticacionValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/eliminarDepartamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DepartamentoResponse eliminarDepartamento(Departamento obj) {
            object[] results = this.Invoke("eliminarDepartamento", new object[] {
                        obj});
            return ((DepartamentoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void eliminarDepartamentoAsync(Departamento obj) {
            this.eliminarDepartamentoAsync(obj, null);
        }
        
        /// <remarks/>
        public void eliminarDepartamentoAsync(Departamento obj, object userState) {
            if ((this.eliminarDepartamentoOperationCompleted == null)) {
                this.eliminarDepartamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarDepartamentoOperationCompleted);
            }
            this.InvokeAsync("eliminarDepartamento", new object[] {
                        obj}, this.eliminarDepartamentoOperationCompleted, userState);
        }
        
        private void OneliminarDepartamentoOperationCompleted(object arg) {
            if ((this.eliminarDepartamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarDepartamentoCompleted(this, new eliminarDepartamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class Autenticacion : System.Web.Services.Protocols.SoapHeader {
        
        private string usuarioField;
        
        private string contrasenaField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <comentarios/>
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <comentarios/>
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                this.contrasenaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DepartamentoResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class Response {
        
        private bool correctoField;
        
        private string errorField;
        
        private string numeroField;
        
        /// <comentarios/>
        public bool correcto {
            get {
                return this.correctoField;
            }
            set {
                this.correctoField = value;
            }
        }
        
        /// <comentarios/>
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <comentarios/>
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DepartamentoResponse : Response {
        
        private Departamento objetoField;
        
        /// <comentarios/>
        public Departamento objeto {
            get {
                return this.objetoField;
            }
            set {
                this.objetoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Departamento {
        
        private long iD_DEPARTAMENTOField;
        
        private string nOM_DEPARTAMENTOField;
        
        /// <comentarios/>
        public long ID_DEPARTAMENTO {
            get {
                return this.iD_DEPARTAMENTOField;
            }
            set {
                this.iD_DEPARTAMENTOField = value;
            }
        }
        
        /// <comentarios/>
        public string NOM_DEPARTAMENTO {
            get {
                return this.nOM_DEPARTAMENTOField;
            }
            set {
                this.nOM_DEPARTAMENTOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void crearDepartamentoCompletedEventHandler(object sender, crearDepartamentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class crearDepartamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal crearDepartamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DepartamentoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DepartamentoResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void editarDepartamentoCompletedEventHandler(object sender, editarDepartamentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class editarDepartamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal editarDepartamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DepartamentoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DepartamentoResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void buscarPrimeroDepartamentoCompletedEventHandler(object sender, buscarPrimeroDepartamentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarPrimeroDepartamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarPrimeroDepartamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Departamento Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Departamento)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void buscarDepartamentoCompletedEventHandler(object sender, buscarDepartamentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarDepartamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarDepartamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Departamento[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Departamento[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void buscarPaginacionDepartamentoCompletedEventHandler(object sender, buscarPaginacionDepartamentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarPaginacionDepartamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarPaginacionDepartamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Departamento[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Departamento[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void listarDepartamentoCompletedEventHandler(object sender, listarDepartamentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarDepartamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarDepartamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Departamento[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Departamento[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void listarPaginacionDepartamentoCompletedEventHandler(object sender, listarPaginacionDepartamentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarPaginacionDepartamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarPaginacionDepartamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Departamento[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Departamento[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void contarBusquedaDepartamentoCompletedEventHandler(object sender, contarBusquedaDepartamentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class contarBusquedaDepartamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal contarBusquedaDepartamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void eliminarDepartamentoCompletedEventHandler(object sender, eliminarDepartamentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eliminarDepartamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eliminarDepartamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DepartamentoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DepartamentoResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591